### ISSUE TITLE
False positive - writable directories

### ISSUE THREAD

**Issue by 0xElessar** [AlessandroZ/BeRoot#34]
Hey,

thank you for the tool. Thank you for your hard work.

Could you explain why the tool reports writable directory, while it is not really writable by a user? I have so many false positives reporting writing possible to c:\ or c:\windows\system32 .

thanks

**Comment by AlessandroZ** [comment]
Hi @0xElessar, 

It's weird because at the beginning I had lots of false positive when I read the directory options to test if it's writable, so I decided to create a tmp file to be sure the directory was writable [(code](https://github.com/AlessandroZ/BeRoot/blob/master/Windows/BeRoot/beroot/modules/checks/path_manipulation_checks.py#L21)). So it should not give you any false positive. I don't understand why it's happening. 

I imagine, you have already tried to create a file on these directories using the same privilege level you have launched the tool.

**Comment by 0xElessar** [comment]
Thank you for your response, Allessandro.

Indeed I have tried and the attempt failed. Maybe I am using outdated version or something. I am using the latest compiled .exe version, which comes from 2017. Maybe this is a problem?

**Comment by AlessandroZ** [comment]
No this update has been done long time ago (I think even that the project was online). So without debugging, I cannot help you, it never happen to me. Sorry.

**Comment by 0xElessar** [comment]
Thank you.
