### ISSUE TITLE
Issue with check_webclient

### ISSUE THREAD

**Issue by fsacer** [AlessandroZ/BeRoot#5]
While running this on Windows Server 2008 R2 x64 (Metasploitable 3) I get this error:
```
-------------- Error on: check_webclient --------------
Traceback (most recent call last):
  File "beroot\run_checks.py", line 315, in check_all
  File "beroot\run_checks.py", line 277, in check_webclient
  File "beroot\modules\checks\webclient\webclient.py", line 187, in run
  File "beroot\modules\checks\webclient\webclient.py", line 130, in isServiceRunning
error: (1060, 'OpenService', 'The specified service does not exist as an installed service.')


[!] Elapsed time = 0.18799996376
```
I'm using version 1 x64 precompiled binary.

**Comment by AlessandroZ** [comment]
This error means that a non existent service is trying to be opened. I don't know which one when I see your error message.  

I cannot reproduce the error because I don't have access to a 2008 R2 right now.   

If you want to check it, I will appreciate. Try to see if the "webclient" service exists on this windows. You could check on a cmd launched with admin privileges: "sc start webclient". 
If you have an error message with the 1060 error code, it means that it has not been found and the attack cannot be done on this target. 

If it works, you can find the service name which cannot be found printing the value of "service_name" on this  [function](https://github.com/AlessandroZ/BeRoot/blob/master/BeRoot/beroot/modules/checks/webclient/webclient.py#L135)

Thank you for your help.

**Comment by fsacer** [comment]
Probably webclient service did not exist. It would be nice if you would catch the error so the program doesn't crash.

**Comment by AlessandroZ** [comment]
The program doesn't crash, it just prints the stacktrace to be able to debug the error, but it continues, that's why you could see the last line:
`[!] Elapsed time = 0.18799996376`

**Comment by fsacer** [comment]
My bad looks like output got a bit truncated through remote shell when I was using it. This can be closed then.
